[project]
name = "szrpc"
dynamic = ["version"]
description = " Simple ZeroMQ RPC in Python"
readme = "README.rst"
readme-content-type = "text/x-rst"
license = "MIT"
authors = [
    {name = "Michel Fodje",email = "michel.fodje@lightsource.ca"}
]
keywords = ["RPC", "ZeroMQ", "Networking", "Development"]
classifiers = [
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]


[project.urls]
Homepage = "https://github.com/michel4j/swift-rpc"
Issues = "https://github.com/michel4j/swift-rpc/issues"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry]
packages = [
    { include = "szrpc", from = "." },
]
include = [
    {path = "README.rst", format = ["sdist"]},
]
version = "0.0.0"

[tool.poetry.dependencies]
python = ">=3.9,<3.15"
pyzmq = ">=27.1.0"
msgpack = ">=1.1.0"

# optional dependencies
fastapi = { version = ">=0.127.0,<0.140.0", optional = true }
uvicorn = { version = ">=0.39.0,<0.51.0", optional = true }
pygobject = { version = ">=3.54.5,<4.0.0", optional = true }
pyside6 = { version = ">=6.10.3,<7.0.0", optional = true }


[tool.poetry.extras]
dash = ["fastapi", "uvicorn"]
dev = ["pygobject", "pyside6"]
qt = ["pyside6"]
gtk = ["pygobject"]
all = ["fastapi", "uvicorn", "pygobject", "pyside6"]

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
format = "{base}.{revision}{distance}"
